name: Update Documentation
description: Update the documentation for your repository
author: git-biswojit

inputs:
  document_repo_url:
    description: "Document repository URL(owner/repo) to clone"
    required: true
  document_repo_token:
    description: "GitHub token to clone the documentation repository"
    required: true
  agent_release_token:
    description: "Token to download the Python wheel from a private repository"
    required: true
  mongo_db_uri:
    description: "MongoDB connection URI"
    required: true
  db_name:
    description: "Name of the MongoDB database/collection"
    required: true
  google_genai_use_vertexai:
    description: "Set to 'false' to use Gemini API key, 'true' to use Vertex AI with service account(default)"
    required: false
    default: "true"
  google_cloud_project:
    description: "Google Cloud project name (required if using Vertex AI)"
    required: false
  google_cloud_location:
    description: "Google Cloud project location (set to 'global' if unsure)"
    required: false
    default: "global"
  sa_key_json:
    description: "Service Account key JSON (pass from secret)"
    required: false
  google_api_key:
    description: "Gemini API key (required if not using Vertex AI)"
    required: false
  source_repo_path:
    description: "Path to the source code repository (local dev only)"
    required: false
    default: "api"
  readme_repo_path:
    description: "Path to the readme documentation repository (local dev only)"
    required: false
    default: "readme-doc"

runs:
  using: "composite"
  steps:
    - name: "Checkout Source Code (Current Repo)"
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.source_repo_path }}
        fetch-depth: 0

    - name: "Clone Documentation Repository (readme)"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.document_repo_url }}
        path: ${{ inputs.readme_repo_path }}
        token: ${{ inputs.document_repo_token }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Download latest wheel from agent repo
      uses: robinraju/release-downloader@v1.11
      with:
        repository: git-biswojit/readme_automation
        token: ${{ inputs.agent_release_token }}
        latest: true
        fileName: '*.whl'
        out-file-path: wheel_dist
        extract: false

    - name: Install the wheel
      shell: bash
      run: pip install wheel_dist/*.whl

    - name: Configure GOOGLE_APPLICATION_CREDENTIALS from sa_key_json
      shell: bash
      run: |
        echo '${{ inputs.sa_key_json }}' > "$RUNNER_TEMP/gcp-key.json"
        echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-key.json" >> "$GITHUB_ENV"

    - name: Run Readme Automation
      shell: bash
      env:
        MONGO_DB_URI: ${{ inputs.mongo_db_uri }}
        DB_NAME: ${{ inputs.db_name }}
        GOOGLE_GENAI_USE_VERTEXAI: ${{ inputs.google_genai_use_vertexai }}
        GOOGLE_CLOUD_PROJECT: ${{ inputs.google_cloud_project }}
        GOOGLE_CLOUD_LOCATION: ${{ inputs.google_cloud_location }}
        GOOGLE_API_KEY: ${{ inputs.google_api_key }}
        SOURCE_REPO_PATH: ${{ github.workspace }}/${{ inputs.source_repo_path }}
        README_REPO_PATH: ${{ github.workspace }}/${{ inputs.readme_repo_path }}
        SOURCE_REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      run: |
        echo "=== RUNNING THE AGENT ==="
        start

branding:
  color: 'blue'
  icon: 'star'
